#!/bin/bash/
while IFS=';' read col1 col2
do
echo '				<tr>'
echo '				    <td class="thumbnail-img">'
echo '					<a href="#">'
echo '									<img class="img-fluid" src="images/SSEP'$col1'.jpg" alt="" />'
echo '								</a>'
echo '				    </td>'
echo '				    <td class="name-pr">'
echo '					<a href="#">'
#echo '									Capitulo '$col1' '$col2''
echo '									Capitulo '$col1''
echo '								</a>'
echo '				    </td>'
echo '				    <td class="price-pr">'
echo '					<a href="saint-seiya/SS-'$col1'.mp4">'
echo '									Online'
echo '								</a>'
echo '				    </td>'
echo '				    <!--td class="quantity-box"><input type="number" size="4" value="1" min="0" step="1" class="c-input-text qty text"></td-->'
echo '				    <td class="total-pr">'
echo '					<a href="saint-seiya/SS-'$col1'.mkv" download="SaintSeiya-'$col1'">'
echo '									Descargar'
echo '								</a>' 
echo '				    </td>'
echo '				    <!--td class="remove-pr">'
echo '					<a href="#">'
echo '									<i class="fas fa-times"></i>'
echo '								</a>'
echo '				    </td-->'
echo '				</tr>'
done < saint-seiya-avi.csv
